2025-02-05 15:24:15,912 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2025-02-05 15:24:15,913 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2025-02-05 15:24:15,914 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "tamjid.rahman@valon.com", --configuration: "default", --format: "value(name)", PROJECT_ID_OR_NUMBER: "prod-peach-street"]
2025-02-05 15:24:15,926 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2025-02-05 15:24:16,071 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/prod-peach-street?alt=json HTTP/1.1" 429 None
2025-02-05 15:24:16,072 DEBUG    root            Chosen display Format:default
2025-02-05 15:24:16,095 DEBUG    root            Chosen display Format:default
2025-02-05 15:24:16,096 DEBUG    root            Chosen display Format:default
2025-02-05 15:24:16,096 DEBUG    root            (gcloud.projects.describe) RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:32555940559'.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/32555940559
    quota_limit: ReadRequestsPerMinutePerProject
    quota_limit_value: '2400'
    quota_location: global
    quota_metric: cloudresourcemanager.googleapis.com/read_requests
    service: cloudresourcemanager.googleapis.com
  reason: RATE_LIMIT_EXCEEDED
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Request a higher quota limit.
    url: https://cloud.google.com/docs/quotas/help/request_increase
Traceback (most recent call last):
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 815, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/surface/projects/describe.py", line 51, in Run
    return projects_api.Get(project_ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 129, in Get
    return client.projects.Get(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 758, in Get
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamjid/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/projects/prod-peach-street?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Wed, 05 Feb 2025 20:24:16 GMT', 'server': 'ESF', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'server-timing': 'gfet4t7; dur=40', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 429}>, content <{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:32555940559'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "RATE_LIMIT_EXCEEDED",
        "domain": "googleapis.com",
        "metadata": {
          "quota_metric": "cloudresourcemanager.googleapis.com/read_requests",
          "quota_limit": "ReadRequestsPerMinutePerProject",
          "quota_limit_value": "2400",
          "consumer": "projects/32555940559",
          "service": "cloudresourcemanager.googleapis.com",
          "quota_location": "global"
        }
      },
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Request a higher quota limit.",
            "url": "https://cloud.google.com/docs/quotas/help/request_increase"
          }
        ]
      }
    ]
  }
}
>
2025-02-05 15:24:16,097 ERROR    root            (gcloud.projects.describe) RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:32555940559'.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    consumer: projects/32555940559
    quota_limit: ReadRequestsPerMinutePerProject
    quota_limit_value: '2400'
    quota_location: global
    quota_metric: cloudresourcemanager.googleapis.com/read_requests
    service: cloudresourcemanager.googleapis.com
  reason: RATE_LIMIT_EXCEEDED
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Request a higher quota limit.
    url: https://cloud.google.com/docs/quotas/help/request_increase
